// Code generated by pricing/internal/gen. DO NOT EDIT.
//
// Regenerate with: make pricing-table COMMIT=<litellm commit sha>
//
// Source: BerriAI/litellm model_prices_and_context_window.json. These are VENDOR
// LIST prices for the first-party Anthropic endpoint. A gateway that bills below
// list — most internal LiteLLM deployments do — is OVERSTATED by this table, and
// an operator corrects it with a host-scoped `pricing:` entry, which outranks
// anything bundled. Rates are written in the unit providers publish, dollars per
// million tokens, divided by a constant so the compiler folds each one exactly.

package pricing

// BundledUpstreamCommit is the BerriAI/litellm commit this table was generated
// from. Pinned so "refresh the rates" is a scripted diff against a known base
// rather than a measurement exercise, and so the golden test can prove the
// checked-in table still matches its snapshot.
const BundledUpstreamCommit = "ee7c7e14f3dd7c4c3930a423440ec26427e2c554"

// Bundled returns the price table shipped in the binary.
//
// Deeply copied, thresholds included. The rows are package state shared by every
// Registry, so a caller that appended to the slice — or wrote through a row's
// Thresholds, which a shallow copy would still alias — would corrupt every later
// NewTable in the process.
func Bundled() []Entry {
	out := make([]Entry, len(bundledEntries))
	for i, e := range bundledEntries {
		if e.Rates.Thresholds != nil {
			e.Rates.Thresholds = append([]ContextThreshold(nil), e.Rates.Thresholds...)
		}
		out[i] = e
	}
	return out
}

var bundledEntries = []Entry{
	{Host: "*", Model: "claude-3-7-sonnet-20250219", Prov: ProvBundled, Rates: Rates{
		Base: [numTiers]float64{TierInput: 3.0 / 1000000, TierCacheWrite: 3.75 / 1000000, TierCacheRead: 0.3 / 1000000, TierOutput: 15.0 / 1000000},
		Set:  [numTiers]bool{TierInput: true, TierCacheWrite: true, TierCacheRead: true, TierOutput: true},
	}},
	{Host: "*", Model: "claude-3-haiku-20240307", Prov: ProvBundled, Rates: Rates{
		Base: [numTiers]float64{TierInput: 0.25 / 1000000, TierCacheWrite: 0.3 / 1000000, TierCacheRead: 0.03 / 1000000, TierOutput: 1.25 / 1000000},
		Set:  [numTiers]bool{TierInput: true, TierCacheWrite: true, TierCacheRead: true, TierOutput: true},
	}},
	{Host: "*", Model: "claude-3-opus-20240229", Prov: ProvBundled, Rates: Rates{
		Base: [numTiers]float64{TierInput: 15.0 / 1000000, TierCacheWrite: 18.75 / 1000000, TierCacheRead: 1.5 / 1000000, TierOutput: 75.0 / 1000000},
		Set:  [numTiers]bool{TierInput: true, TierCacheWrite: true, TierCacheRead: true, TierOutput: true},
	}},
	{Host: "*", Model: "claude-4-opus-20250514", Prov: ProvBundled, Rates: Rates{
		Base: [numTiers]float64{TierInput: 15.0 / 1000000, TierCacheWrite: 18.75 / 1000000, TierCacheRead: 1.5 / 1000000, TierOutput: 75.0 / 1000000},
		Set:  [numTiers]bool{TierInput: true, TierCacheWrite: true, TierCacheRead: true, TierOutput: true},
	}},
	{Host: "*", Model: "claude-4-sonnet-20250514", Prov: ProvBundled, Rates: Rates{
		Base: [numTiers]float64{TierInput: 3.0 / 1000000, TierCacheWrite: 3.75 / 1000000, TierCacheRead: 0.3 / 1000000, TierOutput: 15.0 / 1000000},
		Set:  [numTiers]bool{TierInput: true, TierCacheWrite: true, TierCacheRead: true, TierOutput: true},
		Thresholds: []ContextThreshold{{
			AbovePromptTokens: 200000,
			Rate:              [numTiers]float64{TierInput: 6.0 / 1000000, TierCacheWrite: 7.5 / 1000000, TierCacheRead: 0.6 / 1000000, TierOutput: 22.5 / 1000000},
			Set:               [numTiers]bool{TierInput: true, TierCacheWrite: true, TierCacheRead: true, TierOutput: true},
		}},
	}},
	{Host: "*", Model: "claude-fable-5", Prov: ProvBundled, Rates: Rates{
		Base: [numTiers]float64{TierInput: 10.0 / 1000000, TierCacheWrite: 12.5 / 1000000, TierCacheRead: 1.0 / 1000000, TierOutput: 50.0 / 1000000},
		Set:  [numTiers]bool{TierInput: true, TierCacheWrite: true, TierCacheRead: true, TierOutput: true},
	}},
	{Host: "*", Model: "claude-fable-5-1", Prov: ProvBundled, Rates: Rates{
		Base: [numTiers]float64{TierInput: 10.0 / 1000000, TierCacheWrite: 12.5 / 1000000, TierCacheRead: 0.25 / 1000000, TierOutput: 50.0 / 1000000},
		Set:  [numTiers]bool{TierInput: true, TierCacheWrite: true, TierCacheRead: true, TierOutput: true},
	}},
	{Host: "*", Model: "claude-haiku-4-5", Prov: ProvBundled, Rates: Rates{
		Base: [numTiers]float64{TierInput: 1.0 / 1000000, TierCacheWrite: 1.25 / 1000000, TierCacheRead: 0.09999999999999999 / 1000000, TierOutput: 5.0 / 1000000},
		Set:  [numTiers]bool{TierInput: true, TierCacheWrite: true, TierCacheRead: true, TierOutput: true},
	}},
	{Host: "*", Model: "claude-haiku-4-5-20251001", Prov: ProvBundled, Rates: Rates{
		Base: [numTiers]float64{TierInput: 1.0 / 1000000, TierCacheWrite: 1.25 / 1000000, TierCacheRead: 0.09999999999999999 / 1000000, TierOutput: 5.0 / 1000000},
		Set:  [numTiers]bool{TierInput: true, TierCacheWrite: true, TierCacheRead: true, TierOutput: true},
	}},
	{Host: "*", Model: "claude-mythos-5", Prov: ProvBundled, Rates: Rates{
		Base: [numTiers]float64{TierInput: 10.0 / 1000000, TierCacheWrite: 12.5 / 1000000, TierCacheRead: 1.0 / 1000000, TierOutput: 50.0 / 1000000},
		Set:  [numTiers]bool{TierInput: true, TierCacheWrite: true, TierCacheRead: true, TierOutput: true},
	}},
	{Host: "*", Model: "claude-mythos-5-1", Prov: ProvBundled, Rates: Rates{
		Base: [numTiers]float64{TierInput: 10.0 / 1000000, TierCacheWrite: 12.5 / 1000000, TierCacheRead: 0.25 / 1000000, TierOutput: 50.0 / 1000000},
		Set:  [numTiers]bool{TierInput: true, TierCacheWrite: true, TierCacheRead: true, TierOutput: true},
	}},
	{Host: "*", Model: "claude-mythos-preview", Prov: ProvBundled, Rates: Rates{
		Base: [numTiers]float64{TierInput: 10.0 / 1000000, TierCacheWrite: 12.5 / 1000000, TierCacheRead: 1.0 / 1000000, TierOutput: 50.0 / 1000000},
		Set:  [numTiers]bool{TierInput: true, TierCacheWrite: true, TierCacheRead: true, TierOutput: true},
	}},
	{Host: "*", Model: "claude-opus-4-1", Prov: ProvBundled, Rates: Rates{
		Base: [numTiers]float64{TierInput: 15.0 / 1000000, TierCacheWrite: 18.75 / 1000000, TierCacheRead: 1.5 / 1000000, TierOutput: 75.0 / 1000000},
		Set:  [numTiers]bool{TierInput: true, TierCacheWrite: true, TierCacheRead: true, TierOutput: true},
	}},
	{Host: "*", Model: "claude-opus-4-1-20250805", Prov: ProvBundled, Rates: Rates{
		Base: [numTiers]float64{TierInput: 15.0 / 1000000, TierCacheWrite: 18.75 / 1000000, TierCacheRead: 1.5 / 1000000, TierOutput: 75.0 / 1000000},
		Set:  [numTiers]bool{TierInput: true, TierCacheWrite: true, TierCacheRead: true, TierOutput: true},
	}},
	{Host: "*", Model: "claude-opus-4-20250514", Prov: ProvBundled, Rates: Rates{
		Base: [numTiers]float64{TierInput: 15.0 / 1000000, TierCacheWrite: 18.75 / 1000000, TierCacheRead: 1.5 / 1000000, TierOutput: 75.0 / 1000000},
		Set:  [numTiers]bool{TierInput: true, TierCacheWrite: true, TierCacheRead: true, TierOutput: true},
	}},
	{Host: "*", Model: "claude-opus-4-5", Prov: ProvBundled, Rates: Rates{
		Base: [numTiers]float64{TierInput: 5.0 / 1000000, TierCacheWrite: 6.25 / 1000000, TierCacheRead: 0.5 / 1000000, TierOutput: 25.0 / 1000000},
		Set:  [numTiers]bool{TierInput: true, TierCacheWrite: true, TierCacheRead: true, TierOutput: true},
	}},
	{Host: "*", Model: "claude-opus-4-5-20251101", Prov: ProvBundled, Rates: Rates{
		Base: [numTiers]float64{TierInput: 5.0 / 1000000, TierCacheWrite: 6.25 / 1000000, TierCacheRead: 0.5 / 1000000, TierOutput: 25.0 / 1000000},
		Set:  [numTiers]bool{TierInput: true, TierCacheWrite: true, TierCacheRead: true, TierOutput: true},
	}},
	{Host: "*", Model: "claude-opus-4-6", Prov: ProvBundled, Rates: Rates{
		Base: [numTiers]float64{TierInput: 5.0 / 1000000, TierCacheWrite: 6.25 / 1000000, TierCacheRead: 0.5 / 1000000, TierOutput: 25.0 / 1000000},
		Set:  [numTiers]bool{TierInput: true, TierCacheWrite: true, TierCacheRead: true, TierOutput: true},
	}},
	{Host: "*", Model: "claude-opus-4-6-20260205", Prov: ProvBundled, Rates: Rates{
		Base: [numTiers]float64{TierInput: 5.0 / 1000000, TierCacheWrite: 6.25 / 1000000, TierCacheRead: 0.5 / 1000000, TierOutput: 25.0 / 1000000},
		Set:  [numTiers]bool{TierInput: true, TierCacheWrite: true, TierCacheRead: true, TierOutput: true},
	}},
	{Host: "*", Model: "claude-opus-4-7", Prov: ProvBundled, Rates: Rates{
		Base: [numTiers]float64{TierInput: 5.0 / 1000000, TierCacheWrite: 6.25 / 1000000, TierCacheRead: 0.5 / 1000000, TierOutput: 25.0 / 1000000},
		Set:  [numTiers]bool{TierInput: true, TierCacheWrite: true, TierCacheRead: true, TierOutput: true},
	}},
	{Host: "*", Model: "claude-opus-4-7-20260416", Prov: ProvBundled, Rates: Rates{
		Base: [numTiers]float64{TierInput: 5.0 / 1000000, TierCacheWrite: 6.25 / 1000000, TierCacheRead: 0.5 / 1000000, TierOutput: 25.0 / 1000000},
		Set:  [numTiers]bool{TierInput: true, TierCacheWrite: true, TierCacheRead: true, TierOutput: true},
	}},
	{Host: "*", Model: "claude-opus-4-8", Prov: ProvBundled, Rates: Rates{
		Base: [numTiers]float64{TierInput: 5.0 / 1000000, TierCacheWrite: 6.25 / 1000000, TierCacheRead: 0.5 / 1000000, TierOutput: 25.0 / 1000000},
		Set:  [numTiers]bool{TierInput: true, TierCacheWrite: true, TierCacheRead: true, TierOutput: true},
	}},
	{Host: "*", Model: "claude-opus-5", Prov: ProvBundled, Rates: Rates{
		Base: [numTiers]float64{TierInput: 5.0 / 1000000, TierCacheWrite: 6.25 / 1000000, TierCacheRead: 0.5 / 1000000, TierOutput: 25.0 / 1000000},
		Set:  [numTiers]bool{TierInput: true, TierCacheWrite: true, TierCacheRead: true, TierOutput: true},
	}},
	{Host: "*", Model: "claude-sonnet-4-20250514", Prov: ProvBundled, Rates: Rates{
		Base: [numTiers]float64{TierInput: 3.0 / 1000000, TierCacheWrite: 3.75 / 1000000, TierCacheRead: 0.3 / 1000000, TierOutput: 15.0 / 1000000},
		Set:  [numTiers]bool{TierInput: true, TierCacheWrite: true, TierCacheRead: true, TierOutput: true},
		Thresholds: []ContextThreshold{{
			AbovePromptTokens: 200000,
			Rate:              [numTiers]float64{TierInput: 6.0 / 1000000, TierCacheWrite: 7.5 / 1000000, TierCacheRead: 0.6 / 1000000, TierOutput: 22.5 / 1000000},
			Set:               [numTiers]bool{TierInput: true, TierCacheWrite: true, TierCacheRead: true, TierOutput: true},
		}},
	}},
	{Host: "*", Model: "claude-sonnet-4-5", Prov: ProvBundled, Rates: Rates{
		Base: [numTiers]float64{TierInput: 3.0 / 1000000, TierCacheWrite: 3.75 / 1000000, TierCacheRead: 0.3 / 1000000, TierOutput: 15.0 / 1000000},
		Set:  [numTiers]bool{TierInput: true, TierCacheWrite: true, TierCacheRead: true, TierOutput: true},
		Thresholds: []ContextThreshold{{
			AbovePromptTokens: 200000,
			Rate:              [numTiers]float64{TierInput: 6.0 / 1000000, TierCacheWrite: 7.5 / 1000000, TierCacheRead: 0.6 / 1000000, TierOutput: 22.5 / 1000000},
			Set:               [numTiers]bool{TierInput: true, TierCacheWrite: true, TierCacheRead: true, TierOutput: true},
		}},
	}},
	{Host: "*", Model: "claude-sonnet-4-5-20250929", Prov: ProvBundled, Rates: Rates{
		Base: [numTiers]float64{TierInput: 3.0 / 1000000, TierCacheWrite: 3.75 / 1000000, TierCacheRead: 0.3 / 1000000, TierOutput: 15.0 / 1000000},
		Set:  [numTiers]bool{TierInput: true, TierCacheWrite: true, TierCacheRead: true, TierOutput: true},
		Thresholds: []ContextThreshold{{
			AbovePromptTokens: 200000,
			Rate:              [numTiers]float64{TierInput: 6.0 / 1000000, TierCacheWrite: 7.5 / 1000000, TierCacheRead: 0.6 / 1000000, TierOutput: 22.5 / 1000000},
			Set:               [numTiers]bool{TierInput: true, TierCacheWrite: true, TierCacheRead: true, TierOutput: true},
		}},
	}},
	{Host: "*", Model: "claude-sonnet-4-6", Prov: ProvBundled, Rates: Rates{
		Base: [numTiers]float64{TierInput: 3.0 / 1000000, TierCacheWrite: 3.75 / 1000000, TierCacheRead: 0.3 / 1000000, TierOutput: 15.0 / 1000000},
		Set:  [numTiers]bool{TierInput: true, TierCacheWrite: true, TierCacheRead: true, TierOutput: true},
	}},
	{Host: "*", Model: "claude-sonnet-5", Prov: ProvBundled, Rates: Rates{
		Base: [numTiers]float64{TierInput: 2.0 / 1000000, TierCacheWrite: 2.5 / 1000000, TierCacheRead: 0.19999999999999998 / 1000000, TierOutput: 10.0 / 1000000},
		Set:  [numTiers]bool{TierInput: true, TierCacheWrite: true, TierCacheRead: true, TierOutput: true},
	}},
	{Host: "*", Model: "*claude-fable-*", Prov: ProvBundled, Rates: Rates{
		Base: [numTiers]float64{TierInput: 10.0 / 1000000, TierCacheWrite: 12.5 / 1000000, TierCacheRead: 0.25 / 1000000, TierOutput: 50.0 / 1000000},
		Set:  [numTiers]bool{TierInput: true, TierCacheWrite: true, TierCacheRead: true, TierOutput: true},
	}},
	{Host: "*", Model: "*claude-haiku-*", Prov: ProvBundled, Rates: Rates{
		Base: [numTiers]float64{TierInput: 1.0 / 1000000, TierCacheWrite: 1.25 / 1000000, TierCacheRead: 0.09999999999999999 / 1000000, TierOutput: 5.0 / 1000000},
		Set:  [numTiers]bool{TierInput: true, TierCacheWrite: true, TierCacheRead: true, TierOutput: true},
	}},
	{Host: "*", Model: "*claude-mythos-*", Prov: ProvBundled, Rates: Rates{
		Base: [numTiers]float64{TierInput: 10.0 / 1000000, TierCacheWrite: 12.5 / 1000000, TierCacheRead: 0.25 / 1000000, TierOutput: 50.0 / 1000000},
		Set:  [numTiers]bool{TierInput: true, TierCacheWrite: true, TierCacheRead: true, TierOutput: true},
	}},
	{Host: "*", Model: "*claude-opus-*", Prov: ProvBundled, Rates: Rates{
		Base: [numTiers]float64{TierInput: 5.0 / 1000000, TierCacheWrite: 6.25 / 1000000, TierCacheRead: 0.5 / 1000000, TierOutput: 25.0 / 1000000},
		Set:  [numTiers]bool{TierInput: true, TierCacheWrite: true, TierCacheRead: true, TierOutput: true},
	}},
	{Host: "*", Model: "*claude-sonnet-*", Prov: ProvBundled, Rates: Rates{
		Base: [numTiers]float64{TierInput: 2.0 / 1000000, TierCacheWrite: 2.5 / 1000000, TierCacheRead: 0.19999999999999998 / 1000000, TierOutput: 10.0 / 1000000},
		Set:  [numTiers]bool{TierInput: true, TierCacheWrite: true, TierCacheRead: true, TierOutput: true},
	}},
}
